/**
 * FCM push notification service.
 *
 * Sends push notifications via the Firebase Cloud Messaging HTTP v1 API.
 * Uses `google.auth.JWT` (from `googleapis`) with a service-account key to
 * obtain a short-lived bearer token — no extra Firebase SDK required.
 *
 * Required env vars:
 *   FIREBASE_PROJECT_ID           — GCP project ID (e.g. "my-project-12345")
 *   FIREBASE_SERVICE_ACCOUNT_KEY  — full JSON of a service account key file,
 *                                   as a single-line JSON string.
 *
 * If either var is missing, every call returns `{ sent: false, reason: "not_configured" }`
 * and the notification service falls back to email immediately.
 *
 * Device tokens are looked up from `push_tokens` by user_id.  The mobile or web
 * client is responsible for registering tokens via whatever endpoint the app exposes
 * (out of scope for the backend completion plan — this service consumes the stored rows).
 */

import { google } from "googleapis";
import { query } from "../../config/db";

// ─── Public types ─────────────────────────────────────────────────────────────

export interface PushAction {
  label: string;
  actionKey: string;
  /** Signed action token generated by `signedActions.ts`. */
  token: string;
}

export interface SendPushParams {
  userId: string;
  title: string;
  body: string;
  actions: PushAction[];
  /** Optional extra data fields (string → string only, FCM requirement). */
  data?: Record<string, string>;
}

export interface SendPushResult {
  sent: boolean;
  messageId?: string;
  reason?: "not_configured" | "no_token" | "fcm_error";
}

// ─── FCM access token ─────────────────────────────────────────────────────────

interface ServiceAccount {
  client_email: string;
  private_key: string;
}

let _cachedToken: { token: string; expiresAt: number } | null = null;

async function getFcmAccessToken(): Promise<string | null> {
  const serviceAccountRaw = process.env.FIREBASE_SERVICE_ACCOUNT_KEY;
  const projectId = process.env.FIREBASE_PROJECT_ID;
  if (!serviceAccountRaw || !projectId) return null;

  // Reuse cached token if still valid (with a 60-second buffer).
  if (_cachedToken && _cachedToken.expiresAt > Date.now() + 60_000) {
    return _cachedToken.token;
  }

  let serviceAccount: ServiceAccount;
  try {
    serviceAccount = JSON.parse(serviceAccountRaw) as ServiceAccount;
  } catch {
    console.error(
      "[push.service] FIREBASE_SERVICE_ACCOUNT_KEY is not valid JSON",
    );
    return null;
  }

  try {
    // google-auth-library v10 removed the positional constructor
    // `new JWT(email, keyFile, key, scopes)` — it now only accepts an options object
    // (`constructor(options?: JWTOptions)`). The old call still *ran*, but no longer
    // type-checks, which broke `npm run build` and therefore every Vercel deploy.
    const auth = new google.auth.JWT({
      email: serviceAccount.client_email,
      key: serviceAccount.private_key,
      scopes: ["https://www.googleapis.com/auth/firebase.messaging"],
    });
    const { token, res } = await auth.getAccessToken();
    if (!token) return null;

    // Cache the token. Google JWTs are valid for 1 h.
    const expiresIn =
      (res?.data as { expires_in?: number } | null)?.expires_in ?? 3600;
    _cachedToken = { token, expiresAt: Date.now() + expiresIn * 1000 };
    return token;
  } catch (err) {
    console.error("[push.service] Failed to get FCM access token:", err);
    return null;
  }
}

// ─── Device token lookup ──────────────────────────────────────────────────────

async function getUserPushTokens(userId: string): Promise<string[]> {
  const res = await query<{ token: string }>(
    "SELECT token FROM push_tokens WHERE user_id = $1",
    [userId],
  );
  return res.rows.map((r) => r.token);
}

// ─── FCM v1 send ──────────────────────────────────────────────────────────────

/**
 * Send a push notification to a user's registered device(s).
 *
 * Only sends to the first registered token (targeting all devices via multicast
 * is a future enhancement).
 */
export async function sendPushNotification(
  params: SendPushParams,
): Promise<SendPushResult> {
  const projectId = process.env.FIREBASE_PROJECT_ID;
  if (!projectId || !process.env.FIREBASE_SERVICE_ACCOUNT_KEY) {
    console.log(
      "[push.service] FCM is not configured — skipping push delivery.",
    );
    return { sent: false, reason: "not_configured" };
  }

  const pushTokens = await getUserPushTokens(params.userId);
  if (pushTokens.length === 0) {
    console.log(
      `[push.service] No push tokens registered for user=${params.userId}`,
    );
    return { sent: false, reason: "no_token" };
  }

  const accessToken = await getFcmAccessToken();
  if (!accessToken) {
    return { sent: false, reason: "fcm_error" };
  }

  // Serialize actions into the FCM data payload.
  // FCM data values must be strings, so serialize the actions array as JSON.
  const dataPayload: Record<string, string> = {
    ...(params.data ?? {}),
    actions: JSON.stringify(params.actions),
  };

  const fcmToken = pushTokens[0]; // Send to the first device; extend for multicast.
  const url = `https://fcm.googleapis.com/v1/projects/${projectId}/messages:send`;

  const requestBody = {
    message: {
      token: fcmToken,
      notification: { title: params.title, body: params.body },
      data: dataPayload,
      android: { priority: "high" as const },
      apns: {
        headers: { "apns-priority": "10" },
      },
    },
  };

  let response: Response;
  try {
    response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${accessToken}`,
      },
      body: JSON.stringify(requestBody),
    });
  } catch (err) {
    console.error("[push.service] Network error calling FCM:", err);
    return { sent: false, reason: "fcm_error" };
  }

  if (!response.ok) {
    const text = await response.text();
    console.error(
      `[push.service] FCM returned ${response.status}: ${text.slice(0, 300)}`,
    );
    return { sent: false, reason: "fcm_error" };
  }

  const data = (await response.json()) as { name?: string };
  return { sent: true, messageId: data.name };
}
